version: '3.3'

services:
  pg:
    build: services/db
    volumes:
      - pg:/var/lib/postgresql/data
      - ./:/tmp/db
      - ../src:/tmp/db/src
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    ports:
      - '5432:5432'
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 5001:5000
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pg:
  web:

