CREATE TABLE playercareerstats (
	"PLAYER_ID" FLOAT NOT NULL, 
	"LEAGUE_ID" FLOAT NOT NULL, 
	"Team_ID" BOOLEAN NOT NULL, 
	"GP" FLOAT NOT NULL, 
	"GS" FLOAT, 
	"MIN" FLOAT, 
	"FGM" FLOAT NOT NULL, 
	"FGA" FLOAT NOT NULL, 
	"FG_PCT" FLOAT NOT NULL, 
	"FG3M" FLOAT, 
	"FG3A" FLOAT, 
	"FG3_PCT" FLOAT, 
	"FTM" FLOAT NOT NULL, 
	"FTA" FLOAT NOT NULL, 
	"FT_PCT" FLOAT NOT NULL, 
	"OREB" FLOAT, 
	"DREB" FLOAT, 
	"REB" FLOAT, 
	"AST" FLOAT NOT NULL, 
	"STL" FLOAT, 
	"BLK" FLOAT, 
	"TOV" FLOAT, 
	"PF" FLOAT NOT NULL, 
	"PTS" FLOAT NOT NULL
);

CREATE INDEX ON playercareerstats ("PLAYER_ID");
CREATE INDEX ON playercareerstats ("Team_ID");

